name: yapilacaklar_listesi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
  cloud_firestore: 4.14.0
  google_sign_in: 6.2.1
  sign_in_with_apple: ^5.0.0
  flutter_facebook_auth: 6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1
  firebase_auth_platform_interface: 7.0.9
  firebase_core_platform_interface: 5.0.0
  firebase_storage_platform_interface: 5.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/

