// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2wYEd_FdZnJf4VBRyn3mvg_CfMm22J3I',
    appId: '1:1073681734239:web:793f594bfebf9e274719ea',
    messagingSenderId: '1073681734239',
    projectId: 'yu-gi-oh--gx',
    authDomain: 'yu-gi-oh--gx.firebaseapp.com',
    storageBucket: 'yu-gi-oh--gx.appspot.com',
    measurementId: 'G-V4EKXJMXG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUpzmuS6UsweRbwhSQFHF4ldLGg0597A4',
    appId: '1:1073681734239:android:fc719f90729745854719ea',
    messagingSenderId: '1073681734239',
    projectId: 'yu-gi-oh--gx',
    storageBucket: 'yu-gi-oh--gx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbpHCG7wK5bBmRR-tHepgL8gxRNgOzCH4',
    appId: '1:1073681734239:ios:60243708a99139f34719ea',
    messagingSenderId: '1073681734239',
    projectId: 'yu-gi-oh--gx',
    storageBucket: 'yu-gi-oh--gx.appspot.com',
    iosBundleId: 'com.example.yugiOhGxDatabase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbpHCG7wK5bBmRR-tHepgL8gxRNgOzCH4',
    appId: '1:1073681734239:ios:53652c76d651470e4719ea',
    messagingSenderId: '1073681734239',
    projectId: 'yu-gi-oh--gx',
    storageBucket: 'yu-gi-oh--gx.appspot.com',
    iosBundleId: 'com.example.yugiOhGxDatabase.RunnerTests',
  );
}
