// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAsmkP69cijqLbei0pj86ye9d8BynVGoU',
    appId: '1:914076867847:web:a64ed7ee22d11df537f9a2',
    messagingSenderId: '914076867847',
    projectId: 'movie-database-124f9',
    authDomain: 'movie-database-124f9.firebaseapp.com',
    storageBucket: 'movie-database-124f9.appspot.com',
    measurementId: 'G-CBN0ZL0BP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi5gWdUMwERrGnE5M4sf60rwHxcWLTo7c',
    appId: '1:914076867847:android:6afe7e7a8a65bd8337f9a2',
    messagingSenderId: '914076867847',
    projectId: 'movie-database-124f9',
    storageBucket: 'movie-database-124f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkmPp8qd3JxqOq4tKb1hNGQnZl5_qrSyg',
    appId: '1:914076867847:ios:8aeca61f68719a9337f9a2',
    messagingSenderId: '914076867847',
    projectId: 'movie-database-124f9',
    storageBucket: 'movie-database-124f9.appspot.com',
    iosBundleId: 'com.example.movieDatabase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkmPp8qd3JxqOq4tKb1hNGQnZl5_qrSyg',
    appId: '1:914076867847:ios:7e894ff0b22f402c37f9a2',
    messagingSenderId: '914076867847',
    projectId: 'movie-database-124f9',
    storageBucket: 'movie-database-124f9.appspot.com',
    iosBundleId: 'com.example.movieDatabase.RunnerTests',
  );
}
